name: Build Unsigned iOS IPA

on:
  workflow_dispatch: # This allows you to trigger the build manually

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_FIREBASE_API_KEY=${{ secrets.EXPO_PUBLIC_FIREBASE_API_KEY }}" >> .env
          echo "EXPO_PUBLIC_FIREBASE_APP_ID=${{ secrets.EXPO_PUBLIC_FIREBASE_APP_ID }}" >> .env
          echo "EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "EXPO_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.EXPO_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env
          echo "EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME=${{ secrets.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET=${{ secrets.EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET }}" >> .env
          echo "EXPO_PUBLIC_TENOR_API_KEY=${{ secrets.EXPO_PUBLIC_TENOR_API_KEY }}" >> .env

      - name: Generate iOS native code
        run: npx expo prebuild -p ios

      - name: Install iOS Pods
        run: |
          cd ios
          pod install

      - name: Compile Unsigned App
        run: |
          cd ios
          # Strip the push notification entitlement since Apple strictly blocks unsigned builds with aps-environment
          /usr/libexec/PlistBuddy -c "Delete :aps-environment" HopON/HopON.entitlements || true

          export NODE_BINARY=$(command -v node)
          set -o pipefail
          xcodebuild -workspace HopON.xcworkspace -scheme HopON -configuration Release -sdk iphoneos OBJROOT=$PWD/build SYMROOT=$PWD/build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Package into IPA
        run: |
          cd ios
          mkdir -p Payload
          cp -r build/Release-iphoneos/HopON.app Payload/
          zip -r HopON.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HopON-iOS-App
          path: ios/HopON.ipa
